apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app/
  - observability/

images:
  - name: lmacademy/web-translator-frontend
    newTag: v1.3.0
  - name: lmacademy/web-translator-worker
    newTag: v1.3.0