services:
  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - observability
    restart: unless-stopped
  loki:
    image: grafana/loki:3.6.6
    container_name: loki
    user: root
    command:
      - "-config.file=/etc/loki/loki.yaml"
      - "-target=all"
    volumes:
      - ./loki-config.yaml:/etc/loki/loki.yaml:ro
      - loki-data:/loki
      - loki-wal:/wal
    ports:
      - "3100:3100"
    networks:
      - observability
    restart: unless-stopped
  tempo:
    image: grafana/tempo:2.10.1
    container_name: tempo
    command:
      - "-config.file=/etc/tempo/tempo.yaml"
      - "-target=all"
    volumes:
      - ./tempo-config.yaml:/etc/tempo/tempo.yaml:ro
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"
    networks:
      - observability
    restart: unless-stopped
  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - observability
    restart: unless-stopped
    depends_on:
      - prometheus
      - loki
      - tempo
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.146.1
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "8888:8888" # OTel Internal metrics
      - "8889:8889" # Prometheus metrics exporter
    networks:
      - observability
      - app
    restart: unless-stopped
    depends_on:
      - prometheus
      - loki
      - tempo

volumes:
  prometheus-data:
  loki-data:
  loki-wal:
  tempo-data:
  grafana-data:
